### ISSUE TITLE
Option B installation - 'rm' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by malindasuhash** [Adyen/adyen-3ds2-js-utils#3]
I was presented with the following:

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @adyen/threeds2-js-utils@1.0.0 build: `rm -rf dist/ && webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @adyen/threeds2-js-utils@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

My npm version is 6.4.1. 
Any idea? The "threeds2-js-utils.js" gets created anyway.

**Comment by Trigalti** [comment]
I am guessing this is a rights / platform issue.
rm means removing the files from specified folder (which might be  OSX only functionality).
I'll take a look at it
