### ISSUE TITLE
Publish as a npm package

### ISSUE THREAD

**Issue by nudge** [Adyen/adyen-3ds2-js-utils#4]
Hi there,

Are there plans to publish this as an npm package?

Cheers,
David

**Comment by Trigalti** [comment]
> Hi there,
> 
> Are there plans to publish this as an npm package?
> 
> Cheers,
> David

Hey @nudge, not at the moment.
This is an ongoing discussion regarding multiple repositories.

However, I will get back to you on this.

**Comment by KrekkieD** [comment]
It hurts maintainability for consumers if this code is not published to NPM. I don't want to do a git clone of this code inside my own repository, and I don't want to do a git clone outside my own repository and copy/paste the resulting dist code into my own repository.

Through NPM I can specify the dependency and import whatever I need to my consuming code, our build will handle the rest when building our dist.

**Comment by Trigalti** [comment]
> It hurts maintainability for consumers if this code is not published to NPM. I don't want to do a git clone of this code inside my own repository, and I don't want to do a git clone outside my own repository and copy/paste the resulting dist code into my own repository.
> 
> Through NPM I can specify the dependency and import whatever I need to my consuming code, our build will handle the rest when building our dist.

Agreed, still, due to security we are not publishing this under NPM just yet.
Closing for now.
